// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThoughtWall.API.Data;

namespace ThoughtWall.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ThoughtWall.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("body");

                    b.Property<int?>("threadId");

                    b.HasKey("Id");

                    b.HasIndex("threadId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ThoughtWall.API.Models.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ThoughtWall.API.Models.Comment", b =>
                {
                    b.HasOne("ThoughtWall.API.Models.Thread", "thread")
                        .WithMany("Comments")
                        .HasForeignKey("threadId");
                });
#pragma warning restore 612, 618
        }
    }
}
